"""In-memory ZIP assembly."""

from __future__ import annotations

import io
import zipfile
from collections.abc import Iterable

from app.domain.schemas import ProcessingReport

REPORT_FILENAME = "report.json"


def _assert_safe_entry_name(name: str) -> None:
    """Guard the ZIP against path traversal.

    Names are generated by :mod:`app.domain.naming` and are safe by construction;
    this asserts the invariant at the boundary so a future change to naming cannot
    quietly produce a zip-slip payload.
    """
    if not name or name.startswith((".", "/", "\\")) or "/" in name or "\\" in name:
        raise ValueError(f"Unsafe ZIP entry name: {name!r}")


def build_zip(entries: Iterable[tuple[str, bytes]], report: ProcessingReport) -> io.BytesIO:
    """Package renamed files plus ``report.json`` into an in-memory ZIP.

    Already-compressed formats (JPEG, PNG, WEBP, GIF) are stored uncompressed:
    re-deflating them costs CPU and saves essentially nothing. Everything else,
    including the report, is deflated.
    """
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in entries:
            _assert_safe_entry_name(name)
            compression = (
                zipfile.ZIP_STORED
                if name.lower().endswith((".jpg", ".jpeg", ".png", ".webp", ".gif"))
                else zipfile.ZIP_DEFLATED
            )
            archive.writestr(name, content, compress_type=compression)

        archive.writestr(
            REPORT_FILENAME,
            report.model_dump_json(indent=2),
            compress_type=zipfile.ZIP_DEFLATED,
        )

    buffer.seek(0)
    return buffer
